CREATE FUNCTION [dsp].[DateTime_EndOfDayTime] (
	@Time DATETIME)
RETURNS DATETIME
AS
BEGIN
	DECLARE @NextDay DATETIME = DATEADD(DAY, 1, CAST(CAST(@Time AS DATE) AS DATETIME));
	SET @Time = DATEADD(MILLISECOND, -10, @NextDay);

	RETURN @Time;
END;